version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: infection/infection
    versions:
    - 0.21.0
    - 0.21.2
    - 0.21.4
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: vimeo/psalm
    versions:
    - 4.6.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.2
