language: php

sudo: false

git:
  depth: false

php:
  - '7.3'
  - '7.4snapshot'
  - 'nightly'

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
  - php: '7.4snapshot'
  - php: 'nightly'

before_script:
  - git checkout -b built-ci-branch
  - composer update --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/psalm
  - vendor/bin/phpcs
  - vendor/bin/infection --min-msi=80 --min-covered-msi=100
